# Generated by Django 5.0.3 on 2024-03-08 11:41

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_account_level_account_lft_account_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial.account'),
        ),
    ]
