# Generated by Django 5.0.3 on 2024-03-08 12:13

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_account_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountcategory',
            field=models.CharField(blank=True, choices=[('Assest', 'Assest'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=255, null=True, verbose_name='Account Category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial.account'),
        ),
    ]
